version: '3'
services:
    app-nginx:
        build:
            context: ./app/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./app:/app
        depends_on:
            - app-php-fpm
        ports:
            - "8888:80"
    app-php-fpm:
        build:
            context: ./app/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app
        depends_on:
            - app-postgres
    app-php-cli:
        build:
            context: ./app/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app
            - composer:/root/.composer/cache
        depends_on:
            - app-postgres
    app-postgres:
        image: postgres:11.2-alpine
        volumes:
            - app-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: app
        ports:
            - "5433:5432"
    app-node:
        image: node:11.13-alpine
        volumes:
            - ./app:/app
        working_dir: /app
    app-node-watch:
        image: node:11.13-alpine
        volumes:
            - ./app:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"


volumes:
    app-postgres:
    composer:
