version: '3'
services:

    # web-server NGINX
    app-nginx:
        build:
            context: ./app/docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./app:/container-app
        depends_on:
            - app-php-fpm
        ports:
            - "8888:80"
        networks:
            - inner

    # Server API: fast cgi process manager for web-server
    app-php-fpm:
        build:
            context: ./app/docker/dev
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/container-app
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.150.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - app-mysql
        networks:
            - inner

    # php cli interface
    app-php-cli:
        build:
            context: ./app/docker/dev
            dockerfile: php-cli.docker
        volumes:
            - ./app:/container-app
            - composer:/root/.composer/cache
        depends_on:
            - app-mysql
        networks:
            - inner

    # mysql database
    app-mysql:
        image: mysql:8
        volumes:
            - app-mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: webapp
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "33061:3306"
        networks:
            - inner

networks:
    inner:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.150.0/28

volumes:
    app-mysql:
    composer: